services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=movie_db
      - POSTGRES_USER=movie_user
      - POSTGRES_PASSWORD=secure_password_123
    ports:
      - "5433:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn movies.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://movie_user:secure_password_123@db:5432/movie_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=secure_key_123
      - DEBUG=True
      - ALLOWED_HOSTS=3.95.239.25,ec2-3-95-239-25.compute-1.amazonaws.com,localhost,127.0.0.1
      - TMDB_API_KEY=f56c4a60d742a43bd902a60a92b83cb3
      - EC2_PUBLIC_IP=3.95.239.25

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume: