version: '3.8'
services:
  web:
    build: .
    command: gunicorn movies.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=movie_db
      - POSTGRES_USER=movie_user
      - POSTGRES_PASSWORD=new_secure_password
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: